# -*- mode: python -*-

# modules
import os

# scons build variables
arm = ARGUMENTS.get('arm', 0)
debug = ARGUMENTS.get('debug', 0)

# environment
env = Environment(CCFLAGS = ['-Wall', '-Wextra', '-Wpedantic'])

# ARM cross compilation
if int(arm):
    env['CXX'] = 'arm-linux-gnueabihf-g++'
    env['AR'] = 'arm-linux-gnueabihf-ar'
    env['RANLIB'] = 'arm-linux-gnueabihf-ranlib'

# debug settings
if int(debug):
    env['CCFLAGS'].append('-g')

# create code executable
env.Program('load', 'main.cpp')
